export const ErrorCodes = {
  // Configuration
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  CONFIG_HOT_RELOAD_FAILED: 'CONFIG_HOT_RELOAD_FAILED',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',

  // Provider
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_AUTH_FAILED: 'PROVIDER_AUTH_FAILED',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',

  // Model
  MODEL_NOT_FOUND: 'MODEL_NOT_FOUND',
  MODEL_CAPABILITY_MISMATCH: 'MODEL_CAPABILITY_MISMATCH',
  MODEL_CONTEXT_EXCEEDED: 'MODEL_CONTEXT_EXCEEDED',

  // Task Queue
  TASK_QUEUE_FULL: 'TASK_QUEUE_FULL',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_CANCELLED: 'TASK_CANCELLED',
  TASK_DEPENDENCY_FAILED: 'TASK_DEPENDENCY_FAILED',

  // Memory / Knowledge
  MEMORY_LOAD_FAILED: 'MEMORY_LOAD_FAILED',
  MEMORY_SAVE_FAILED: 'MEMORY_SAVE_FAILED',
  KNOWLEDGE_RETRIEVAL_FAILED: 'KNOWLEDGE_RETRIEVAL_FAILED',
  KNOWLEDGE_COMPARISON_FAILED: 'KNOWLEDGE_COMPARISON_FAILED',

  // Review / Validation
  REVIEW_FAILED: 'REVIEW_FAILED',
  REGRESSION_DETECTED: 'REGRESSION_DETECTED',

  // Browser
  BROWSER_AUTOMATION_FAILED: 'BROWSER_AUTOMATION_FAILED',
  BROWSER_NAVIGATION_TIMEOUT: 'BROWSER_NAVIGATION_TIMEOUT',
  BROWSER_ENGINE_UNAVAILABLE: 'BROWSER_ENGINE_UNAVAILABLE',

  // Git
  GIT_OPERATION_FAILED: 'GIT_OPERATION_FAILED',
  GIT_REPO_NOT_FOUND: 'GIT_REPO_NOT_FOUND',
  GIT_MERGE_CONFLICT: 'GIT_MERGE_CONFLICT',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];